devtools::test(stop_on_failure = TRUE)
# because throwing an error when a test fails should OBVIOUSLY not be default
